/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Chart Pattern API
 * 차트 패턴 매칭을 위한 API 서버
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';

import type { Symbols } from '../../models';

import { httpClient } from '../../http';
import type { ErrorType } from '../../http';

/**
 * 종목 코드 리스트를 반환합니다.
 * @summary 종목 코드 리스트 조회
 */
export const symbols = (signal?: AbortSignal) => {
  return httpClient<Symbols>({ url: 'http://localhost:3000/api/v1/symbols', method: 'GET', signal });
};

export const getSymbolsQueryKey = () => {
  return ['http://localhost:3000/api/v1/symbols'] as const;
};

export const getSymbolsInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof symbols>>>,
  TError = ErrorType<unknown>,
>(options?: { query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof symbols>>, TError, TData>> }) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSymbolsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof symbols>>> = ({ signal }) => symbols(signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof symbols>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SymbolsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof symbols>>>;
export type SymbolsInfiniteQueryError = ErrorType<unknown>;

export function useSymbolsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof symbols>>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof symbols>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof symbols>>, TError, Awaited<ReturnType<typeof symbols>>>,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSymbolsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof symbols>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof symbols>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof symbols>>, TError, Awaited<ReturnType<typeof symbols>>>,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSymbolsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof symbols>>>,
  TError = ErrorType<unknown>,
>(
  options?: { query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof symbols>>, TError, TData>> },
  queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 종목 코드 리스트 조회
 */

export function useSymbolsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof symbols>>>,
  TError = ErrorType<unknown>,
>(
  options?: { query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof symbols>>, TError, TData>> },
  queryClient?: QueryClient
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSymbolsInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSymbolsQueryOptions = <
  TData = Awaited<ReturnType<typeof symbols>>,
  TError = ErrorType<unknown>,
>(options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof symbols>>, TError, TData>> }) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSymbolsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof symbols>>> = ({ signal }) => symbols(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof symbols>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SymbolsQueryResult = NonNullable<Awaited<ReturnType<typeof symbols>>>;
export type SymbolsQueryError = ErrorType<unknown>;

export function useSymbols<TData = Awaited<ReturnType<typeof symbols>>, TError = ErrorType<unknown>>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof symbols>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<Awaited<ReturnType<typeof symbols>>, TError, Awaited<ReturnType<typeof symbols>>>,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSymbols<TData = Awaited<ReturnType<typeof symbols>>, TError = ErrorType<unknown>>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof symbols>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<Awaited<ReturnType<typeof symbols>>, TError, Awaited<ReturnType<typeof symbols>>>,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSymbols<TData = Awaited<ReturnType<typeof symbols>>, TError = ErrorType<unknown>>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof symbols>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 종목 코드 리스트 조회
 */

export function useSymbols<TData = Awaited<ReturnType<typeof symbols>>, TError = ErrorType<unknown>>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof symbols>>, TError, TData>> },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSymbolsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getSymbolsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof symbols>>,
  TError = ErrorType<unknown>,
>(options?: { query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof symbols>>, TError, TData>> }) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSymbolsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof symbols>>> = ({ signal }) => symbols(signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof symbols>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SymbolsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof symbols>>>;
export type SymbolsSuspenseQueryError = ErrorType<unknown>;

export function useSymbolsSuspense<TData = Awaited<ReturnType<typeof symbols>>, TError = ErrorType<unknown>>(
  options: { query: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof symbols>>, TError, TData>> },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSymbolsSuspense<TData = Awaited<ReturnType<typeof symbols>>, TError = ErrorType<unknown>>(
  options?: { query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof symbols>>, TError, TData>> },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSymbolsSuspense<TData = Awaited<ReturnType<typeof symbols>>, TError = ErrorType<unknown>>(
  options?: { query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof symbols>>, TError, TData>> },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary 종목 코드 리스트 조회
 */

export function useSymbolsSuspense<TData = Awaited<ReturnType<typeof symbols>>, TError = ErrorType<unknown>>(
  options?: { query?: Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof symbols>>, TError, TData>> },
  queryClient?: QueryClient
): UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSymbolsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions, queryClient) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
