/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Chart Pattern API
 * 차트 패턴 매칭을 위한 API 서버
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

/**
 * 종목 코드 리스트를 반환합니다.
 * @summary 종목 코드 리스트 조회
 */
export const symbolsResponse = zod.object({
  symbols: zod.array(zod.string()).describe("종목 코드 리스트 (예: ['BTCUSDT', 'ETHUSDT'])"),
});
