/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Chart Pattern API
 * 차트 패턴 매칭을 위한 API 서버
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

/**
 * API 서버의 상태를 확인하는 엔드포인트
 * @summary API 서버 상태 확인
 */
export const healthCheckResponse = zod.any();
