/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { http, HttpResponse, delay } from 'msw';

export const getHealthHealthGetMockHandler = (
  overrideResponse?: unknown | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<unknown> | unknown)
) => {
  return http.get('*/health', async info => {
    await delay(1000);
    if (typeof overrideResponse === 'function') {
      await overrideResponse(info);
    }
    return new HttpResponse(null, { status: 200 });
  });
};
export const getHealthCheckMock = () => [getHealthHealthGetMockHandler()];
