/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

/**
 * API 서버의 상태를 확인하는 엔드포인트
 * @summary Health
 */
export const healthHealthGetResponse = zod.any();
