/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Chart Pattern API
 * 차트 패턴 매칭을 위한 API 서버
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type { MutationFunction, QueryClient, UseMutationOptions, UseMutationResult } from '@tanstack/react-query';

import type { ChartMatchingRequest, ChartMatchingResponse, HTTPValidationError } from '../../models';

import { httpClient } from '../../http';
import type { ErrorType } from '../../http';

/**
 * 주어진 기간 동안의 차트 패턴과 유사한 패턴을 찾아 반환합니다.
 * @summary 차트 패턴 매칭 리스트 조회
 */
export const chartMatchingList = (chartMatchingRequest: ChartMatchingRequest, signal?: AbortSignal) => {
  return httpClient<ChartMatchingResponse[]>({
    url: 'http://localhost:3000/api/v1/chart_matching_list',
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: chartMatchingRequest,
    signal,
  });
};

export const getChartMatchingListMutationOptions = <
  TError = ErrorType<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof chartMatchingList>>,
    TError,
    { data: ChartMatchingRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof chartMatchingList>>,
  TError,
  { data: ChartMatchingRequest },
  TContext
> => {
  const mutationKey = ['chartMatchingList'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof chartMatchingList>>,
    { data: ChartMatchingRequest }
  > = props => {
    const { data } = props ?? {};

    return chartMatchingList(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ChartMatchingListMutationResult = NonNullable<Awaited<ReturnType<typeof chartMatchingList>>>;
export type ChartMatchingListMutationBody = ChartMatchingRequest;
export type ChartMatchingListMutationError = ErrorType<HTTPValidationError>;

/**
 * @summary 차트 패턴 매칭 리스트 조회
 */
export const useChartMatchingList = <TError = ErrorType<HTTPValidationError>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof chartMatchingList>>,
      TError,
      { data: ChartMatchingRequest },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof chartMatchingList>>,
  TError,
  { data: ChartMatchingRequest },
  TContext
> => {
  const mutationOptions = getChartMatchingListMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
