/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ChartData } from './chartData';

export interface ChartMatchingResponse {
  /** 차트 데이터 */
  data: ChartData[];
  /** 유사도 점수 (0~1) */
  similarity: number;
  /** 종목 코드 */
  symbol: string;
}
