/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Chart Pattern API
 * 차트 패턴 매칭을 위한 API 서버
 * OpenAPI spec version: 1.0.0
 */
import type { ChartSimilarityBase } from './chartSimilarityBase';

export interface ChartSimilarityList {
  /** 차트 유사도 결과 리스트 */
  similarities: ChartSimilarityBase[];
}
