/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Chart Pattern API
 * 차트 패턴 매칭을 위한 API 서버
 * OpenAPI spec version: 1.0.0
 */

/**
 * 시간 단위 (예: 5m, 1h, 1d)
 */
export type ChartMatchingRequestTimeframe =
  (typeof ChartMatchingRequestTimeframe)[keyof typeof ChartMatchingRequestTimeframe];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChartMatchingRequestTimeframe = {
  NUMBER_1: '1',
  NUMBER_3: '3',
  NUMBER_5: '5',
  NUMBER_15: '15',
  NUMBER_30: '30',
  NUMBER_60: '60',
  NUMBER_120: '120',
  NUMBER_180: '180',
  NUMBER_240: '240',
  D: 'D',
  W: 'W',
} as const;
