/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ChartMatchingRequestTimeframe } from './chartMatchingRequestTimeframe';

export interface ChartMatchingRequest {
  /** 종목 코드 (예: BTCUSDT) */
  symbol: string;
  /** 시간 단위 (예: 5m, 1h, 1d) */
  timeframe: ChartMatchingRequestTimeframe;
  /** 시작 날짜 및 시간 */
  startDate: string;
  /** 종료 날짜 및 시간 */
  endDate: string;
}
