/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Chart Pattern API
 * 차트 패턴 매칭을 위한 API 서버
 * OpenAPI spec version: 1.0.0
 */
import type { ChartSimilarityBasePriceData } from './chartSimilarityBasePriceData';

export interface ChartSimilarityBase {
  end_time: string;
  price_data?: ChartSimilarityBasePriceData;
  similarity: number;
  start_time: string;
  /** 심볼 (예: BTCUSDT, ETHUSDT 등) */
  symbol: string;
  time: string;
}
