/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export interface ChartData {
  /** 날짜 및 시간 */
  x: string;
  /** [시가, 고가, 종가, 저가] */
  y: number[];
}
