/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Chart Pattern API
 * 차트 패턴 매칭을 위한 API 서버
 * OpenAPI spec version: 1.0.0
 */

export interface Symbols {
  /** 종목 코드 리스트 (예: ['BTCUSDT', 'ETHUSDT']) */
  symbols: string[];
}
